bitergia-analytics/bitergia-analytics-plugin

- public/components/kibiter_menu/kibiter_menu.js
This PR changes the observer used to replace the logos on fullscreen mode to only listen for the `class` attribute mutation on `app-wrapper`, which is triggered when entering or exiting the mode. This will avoid looping through other mutations and running `changeBranding` when it's not needed and improve load times.
> Improve fullscreen observer to reduce load times

- common/index.ts
- opensearch_dashboards.json
- package.json
- public/application.tsx
- public/components/kibiter_menu/kibiter_menu.js
- public/components/kibiter_menu/kibiter_menu_style.scss
- public/index.ts
- public/plugin.ts
- server/index.ts
- server/plugin.ts
- server/routes/index.ts
- server/routes/menu.ts
- server/types.ts
This PR adds the possibility to customize the Bitergia top menu colors on OpenSearch Dashboards versions 1.1.0 - 1.2.0.
You can configure the colors on the `opensearch_dashboards.yml` file, under `bitergia_analytics.branding`. For example:
```yaml
bitergia_analytics.branding:
backgroundColor: "#F13333"
textColor: "#FFFFFF"
linkColor: "#FFFFFF"
menuItemColor: "#FFFFFF"
selectedItemColor: "#C00000"
```
On OpenSearch 1.2.0 the logos can be customized on `opensearch_dashboards.yml` too, so I removed the code that replaced them. 
To test it, you can run OpenSearch Dashboards on a [development environment](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#getting-started) and install the plugin or use Docker.
Example `Dockerfile`:
```dockerfile
FROM …
```
> Customize top menu colors

- .github/workflows/release.yml
This workflow automates the creation of a new release on GitHub. The workflow is triggered when a new tag is created. Then, it builds a new version of the plugin and generates a new release uploading the built.
> Add release workflow on GitHub actions

- public/components/dropdown.tsx
- public/components/link.tsx
- public/components/menu.tsx
- public/plugin.tsx
Builds the menu links using the `dashboards` app URL as base. This avoids conflicts with with other app URLs, e.g. index patterns manager.
> Get base URL for links from dashboards app

- public/components/menu.tsx
Changes the base URL on the `setActiveLink` function to match the one on the history object, which was preventing the `selectedItemColor` branding customization from working.
> Fix selectedItemColor customization

- .github/workflows/functional-test.yml
- README.md
- babel.config.js
- common/index.ts
- package.json
- public/app/index.tsx
- public/components/dragDropEditor.tsx
- public/components/formModal.tsx
- public/components/jsonEditor.tsx
- public/components/menu.tsx
- public/plugin.tsx
- public/tests/menu.test.tsx
- public/tests/plugin.test.ts
- server/routes/index.ts
- server/routes/menu.ts
- server/routes/metadashboard.ts
- server/routes/search.ts
- test/api.config.js
- test/api/index.js
- test/mocks.ts
- Unifies the routes to import and export the menu data into a single one with a GET and a PUT method:  `/_plugins/_bap/metadashboard`.
- Updates the README.
- Adds tests for the API. The tests can be run with `yarn test:api`.
- Adds a GitHub action that runs the tests.
> API to import/export menu

- common/index.ts
- test/api/index.js
Replaces `/_plugins/` with `/api/` in the API URLs so that they use each tenant's index instead of the global one.
> Fix API base URL

- .github/workflows/release.yml
Gets the correct Yarn version from OpenSearch Dashboards engines in the release workflow for GitHub actions.
> Fix Yarn version in release workflow

- .github/workflows/unit-test.yml
This PR updates the calls to 'set-output' using the new format to set outputs on the GitHub Actions workflows. More info in: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update deprecated 'set-output' of GitHub Actions

- .github/workflows/release.yml
There were some typos in the filepaths that caused the workflow to fail.
> [ci] Fix typos in the release workflow

- .github/workflows/release.yml
This change affects the 'release' workflow. Setting this permissions the workflow will be able to upload the JS package to GitHub.
> Set GITHU_TOKEN permissions to upload packages

- .github/workflows/release.yml
This commit fix an error on the release workflow.
> Fix typo on action version for 'release' workflow

- public/index.scss
- public/plugin.tsx
Hides the "Switch tenant" selector for all users.
Closes #34.
> Hide "Switch Tenant" selector

- README.md
- public/plugin.tsx
- server/index.ts
Adds the `bitergia_analytics.hideTenantSelector` configuration option to `opensearch_dashboards.yml` to hide or show the tenant selector on the user menu.
> Add configuration option to show/hide tenant selector

- opensearch_dashboards.json
- releases/unreleased/set-opensearch-dashboards-version-to-210.yml
This commit updates the build target to OpenSearch 2.10.
> Set OpenSearch Dashboards version to 2.10

- opensearch_dashboards.json
- releases/unreleased/upgrade-to-opensearch-dashboards-2111.yml
This PR upgrades the OpenSearch Dashboards version to 2.11.1.
> Upgrade OpenSearch to 2.11.1

- public/components/loginButton.tsx
- public/index.scss
- public/plugin.tsx
- public/tests/plugin.test.ts
- releases/unreleased/login-button-for-anonymous-users.yml
- test/mocks.ts
Hides the user icon if the user is 'opendistro_security_anonymous' and adds a button that links to the login page on the header. Removes the API call to get the tenant since it can be gathered from the account info.
> Replace anonymous user icon with login button

- .github/workflows/functional-test.yml
- .github/workflows/release.yml
- .github/workflows/unit-test.yml
This commit updates the version of the actions because some of them are deprecated because Node 16 reached its end of life.
> [CI] Update the version of the actions in the workflows

- .github/workflows/functional-test.yml
- .github/workflows/release.yml
- .github/workflows/unit-test.yml
- opensearch_dashboards.json
- releases/unreleased/upgrade-opensearch-dashboards-version-to-216.yml
Bumps OpenSearch Dashboards to version 2.16 and updates how the Node version is resolved in the GitHub workflows.
> Upgrade to OpenSearch Dashboards 2.16

- .github/workflows/changelog.yml
Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.
> Migrate files for branch rename from master to main
